services:
  telegram-bot-websitechangetracker:
    container_name: telegram-bot-websitechangetracker
    restart: always
    build: .
    environment:
      WebsiteChangeTrackerBot_ACCESS_TOKEN: 
      SQLITE_DB_PATH: websitechangertracker.db
      ADMIN_USER: 
      DEFAULT_JOBS_RUN_TIME: 60
      BRAVE_BROWSER_PATH: ""
      IS_HEADLESS: "False"
      DEFAULT_BROWSER: remotechrome
      SELENIUM_URL: http://selenium-hub:4444/wd/hub
      SCREENSHOT_DELAY: 5
      DB_TYPE: mysql
      DB_HOST: 
      DB_USER: 
      DB_PASSWORD: 
      DB_NAME: 
      USE_FILESYSTEM_TO_SAVE_IMAGES: "False"
      FILESYSTEM_PATH: /data
    volumes:
      - ./data:/data

  selenium-hub:
    image: selenium/hub:4.7.1-20221208
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:4.7.1-20221208
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - "NODE_MAX_SESSION:4"
      - "NODE_MAX_INSTANCES:4"
    deploy:
      replicas: 2
    entrypoint: bash -c 'SE_OPTS="--host $$HOSTNAME" /opt/bin/entry_point.sh'