services:
  telegram-bot-websitechangetracker:
    container_name: telegram-bot-websitechangetracker
    restart: always
    build: .
    volumes:
      - ./data:/data

  selenium-hub:
    image: selenium/hub:4.7.1-20221208
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:4.7.1-20221208
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - NODE_MAX_INSTANCES=5